### ISSUE TITLE
trim error when testing non-passing commits

### ISSUE THREAD

**Issue by ktwbc** [Gherciu/commitlint-jira#1]
When attempting to test a non-passing commit, instead of displaying the error, the actual process errors out on a trim() command

```
git commit -m "test"
husky > commit-msg (node v8.16.0)
/Volumes/dev/api-cpadmin/node_modules/@commitlint/cli/lib/cli.js:119
	throw err;
	^

TypeError: Cannot read property 'trim' of undefined
    at d (/Volumes/dev/api-cpadmin/node_modules/commitlint-plugin-jira-rules/build/index.js:1:3159)
    at a (/Volumes/dev/api-cpadmin/node_modules/commitlint-plugin-jira-rules/build/index.js:1:3963)
    at results.filter.map.entry (/Volumes/dev/api-cpadmin/node_modules/@commitlint/lint/lib/index.js:151:17)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Volumes/dev/api-cpadmin/node_modules/@commitlint/lint/lib/index.js:131:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
husky > commit-msg hook failed (add --no-verify to bypass)
```

**Comment by Gherciu** [comment]
to fix this issue update the packages: 
- commitlint-config-jira@1.0.9
- commitlint-plugin-jira-rules@1.0.11

issue fixed in:  [fix](https://github.com/Gherciu/commitlint-jira/commit/0df8c0e41b6cc9d594d04481d3bb92dfb4ac6add)
